parameters:

    #
    # Entities
    #
    elcodi.core.banner.entity.banner.class: Elcodi\BannerBundle\Entity\Banner
    elcodi.core.banner.entity.banner_zone.class: Elcodi\BannerBundle\Entity\BannerZone

    #
    # Repositories
    #
    elcodi.core.banner.repository.banner.class: Elcodi\BannerBundle\Repository\BannerRepository
    elcodi.core.banner.repository.banner_zone.class: Elcodi\BannerBundle\Repository\BannerZoneRepository

    #
    # Services
    #
    elcodi.core.banner.service.banner_manager.class: Elcodi\BannerBundle\Services\BannerManager

    #
    # Factories
    #
    elcodi.core.banner.factory.banner.class: Elcodi\BannerBundle\Factory\BannerFactory
    elcodi.core.banner.factory.banner_zone.class: Elcodi\BannerBundle\Factory\BannerZoneFactory
