Elcodi\Component\ReferralProgram\Entity\ReferralRule:
    type: entity
    repositoryClass: Elcodi\Component\ReferralProgram\Repository\ReferralRuleRepository
    table: referral_rule
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        referrerType:
            column: referrer_type
            type: string
            length: 255
            nullable: false
        invitedType:
            column: invited_type
            type: string
            length: 255
            nullable: false
        validFrom:
            column: valid_from
            type: datetime
            nullable: false
        validTo:
            column: valid_to
            type: datetime
            nullable: true
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        referrerCoupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            joinColumn:
                name: referrer_coupon_id
                referencedColumnName: id
                nullable: true
        invitedCoupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            joinColumn:
                name: invited_coupon_id
                referencedColumnName: id
                nullable: true

    oneToMany:
        referralLines:
            targetEntity: Elcodi\Component\ReferralProgram\Entity\Interfaces\ReferralLineInterface
            mappedBy: referralRule
