parameters:

    #
    # Factories
    #
    elcodi.core.translator.factory.translator.class: Elcodi\Component\Translator\Factory\TranslatorFactory
    elcodi.core.translator.factory.translation.class: Elcodi\Component\Translator\Factory\TranslationFactory

    #
    # Repositories
    #
    elcodi.core.translator.repository.translation.class: Elcodi\Component\Translator\Repository\TranslationRepository

    #
    # Services
    #
    elcodi.core.translator.services.translation_provider.class: Elcodi\Component\Translator\Services\TranslationProvider
    elcodi.core.translator.services.translator_builder.class: Elcodi\Component\Translator\Services\TranslatorBuilder
    elcodi.core.translator.services.translator.class: Elcodi\Component\Translator\Services\Translator

    #
    # Event Dispatchers
    #
    elcodi.core.translator.event_dispatcher.translator.class: Elcodi\Component\Translator\EventDispatcher\TranslatorEventDispatcher
