services:

    #
    # Event Dispatchers
    #
    elcodi.core.translator.event_dispatcher.translator:
        class: %elcodi.core.translator.event_dispatcher.translator.class%
        arguments:
            event_dispatcher: @event_dispatcher

    elcodi.translator_event_dispatcher:
        alias: elcodi.core.translator.event_dispatcher.translator
