services:

    elcodi.core.translator.services.translation_provider:
        class: %elcodi.core.translator.services.translation_provider.class%
        arguments:
            translation_repository: @elcodi.repository.translation
            translation_factory: @elcodi.factory.translation
            translation_object_manager: @elcodi.object_manager.translation
            cache: @doctrine_cache.providers.elcodi
            cache_prefix: %elcodi.core.translator.cache_prefix%
        tags:
            - { name: kernel.event_listener, event: translator.warmup, method: warmUp }

    elcodi.core.translator.services.translator_builder:
        class: %elcodi.core.translator.services.translator_builder.class%
        arguments:
            translation_provider: @elcodi.core.translator.services.translation_provider
            translator_factory: @elcodi.core.translator.factory.translator
            configuration: %elcodi.core.translator.configuration%

    elcodi.core.translator.services.translator:
        class: %elcodi.core.translator.services.translator.class%
        factory_service: elcodi.core.translator.services.translator_builder
        factory_method: compile

    elcodi.translator:
        alias: elcodi.core.translator.services.translator
