parameters:

    #
    # Entities
    #
    elcodi.core.referral_program.entity.referral_hash.class: Elcodi\ReferralProgramBundle\Entity\ReferralHash
    elcodi.core.referral_program.entity.referral_line.class: Elcodi\ReferralProgramBundle\Entity\ReferralLine
    elcodi.core.referral_program.entity.referral_rule.class: Elcodi\ReferralProgramBundle\Entity\ReferralRule
    elcodi.core.referral_program.entity.invitation.class: Elcodi\ReferralProgramBundle\Entity\Invitation
    elcodi.core.referral_program.entity.invitation_bag.class: Elcodi\ReferralProgramBundle\Entity\InvitationBag

    #
    # Repositories
    #
    elcodi.core.referral_program.repository.referral_hash.class: Elcodi\ReferralProgramBundle\Repository\ReferralHashRepository
    elcodi.core.referral_program.repository.referral_line.class: Elcodi\ReferralProgramBundle\Repository\ReferralLineRepository
    elcodi.core.referral_program.repository.referral_rule.class: Elcodi\ReferralProgramBundle\Repository\ReferralRuleRepository
    elcodi.core.referral_program.repository.invitation.class: Elcodi\ReferralProgramBundle\Repository\InvitationRepository
    elcodi.core.referral_program.repository.invitation_bag.class: Elcodi\ReferralProgramBundle\Repository\InvitationBagRepository

    #
    # Services
    #
    elcodi.core.referral_program.service.referral_program_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralProgramManager
    elcodi.core.referral_program.service.referral_hash_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralHashManager
    elcodi.core.referral_program.service.referral_route_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralRouteManager
    elcodi.core.referral_program.service.referral_coupon_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralCouponManager
    elcodi.core.referral_program.service.referral_rule_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralRuleManager

    #
    # Generators
    #
    elcodi.core.referral_program.generator.hash_generator.class: Elcodi\ReferralProgramBundle\Generator\ReferralHashGenerator

    #
    # Form Types
    #
    elcodi.core.user.form_type.referral_rule.class: Elcodi\ReferralProgramBundle\Form\Type\ReferralRuleType
    elcodi.core.user.form_type.referral_line.class: Elcodi\ReferralProgramBundle\Form\Type\ReferralLineType
    elcodi.core.user.form_type.referral_hash.class: Elcodi\ReferralProgramBundle\Form\Type\ReferralHashType

    #
    # Routes
    #
    elcodi.core.referral_program.routes.loader.class: Elcodi\ReferralProgramBundle\Router\ReferralProgramRoutesLoader

    #
    # EventListeners
    #
    elcodi.core.referral_program.event_listener.referral_program_event_listener.class: Elcodi\ReferralProgramBundle\EventListener\ReferralProgramEventListener

    #
    # Factories
    #
    elcodi.core.referral_program.factory.referral_rule.class: Elcodi\ReferralProgramBundle\Factory\ReferralRuleFactory
    elcodi.core.referral_program.factory.referral_line.class: Elcodi\ReferralProgramBundle\Factory\ReferralLineFactory
    elcodi.core.referral_program.factory.referral_hash.class: Elcodi\ReferralProgramBundle\Factory\ReferralHashFactory
    elcodi.core.referral_program.factory.invitation.class: Elcodi\ReferralProgramBundle\Factory\InvitationFactory
    elcodi.core.referral_program.factory.invitation_bag.class: Elcodi\ReferralProgramBundle\Factory\InvitationBagFactory
