services:

    #
    # Factories
    #
    elcodi.core.referral_program.factory.referral_rule:
        class: %elcodi.core.referral_program.factory.referral_rule.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_rule.class%"]]

    elcodi.core.referral_program.factory.referral_line:
        class: %elcodi.core.referral_program.factory.referral_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_line.class%"]]

    elcodi.core.referral_program.factory.referral_hash:
        class: %elcodi.core.referral_program.factory.referral_hash.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_hash.class%"]]

    elcodi.core.referral_program.factory.invitation:
        class: %elcodi.core.referral_program.factory.invitation.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.invitation.class%"]]

    elcodi.core.referral_program.factory.invitation_bag:
        class: %elcodi.core.referral_program.factory.invitation_bag.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.invitation_bag.class%"]]

    #
    # Entity providers
    #
    elcodi.core.referral_program.entity.referral_rule.instance:
        class: %elcodi.core.referral_program.entity.referral_rule.class%
        factory_service: elcodi.core.referral_program.factory.referral_rule
        factory_method: create
        scope: prototype

    elcodi.core.referral_program.entity.referral_line.instance:
        class: %elcodi.core.referral_program.entity.referral_line.class%
        factory_service: elcodi.core.referral_program.factory.referral_line
        factory_method: create
        scope: prototype

    elcodi.core.referral_program.entity.referral_hash.instance:
        class: %elcodi.core.referral_program.entity.referral_hash.class%
        factory_service: elcodi.core.referral_program.factory.referral_hash
        factory_method: create
        scope: prototype

    elcodi.core.referral_program.entity.invitation.instance:
        class: %elcodi.core.referral_program.entity.invitation.class%
        factory_service: elcodi.core.referral_program.factory.invitation
        factory_method: create
        scope: prototype

    elcodi.core.referral_program.entity.invitation_bag.instance:
        class: %elcodi.core.referral_program.entity.invitation_bag.class%
        factory_service: elcodi.core.referral_program.factory.invitation_bag
        factory_method: create
        scope: prototype
