services:

    #
    # Factories
    #

    #
    # Factory for entity referral_rule
    #
    elcodi.core.referral_program.factory.referral_rule:
        class: %elcodi.core.referral_program.factory.referral_rule.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_rule.class%"]]

    elcodi.factory.referral_rule:
        alias: elcodi.core.referral_program.factory.referral_rule

    #
    # Factory for entity referral_line
    #
    elcodi.core.referral_program.factory.referral_line:
        class: %elcodi.core.referral_program.factory.referral_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_line.class%"]]

    elcodi.factory.referral_line:
        alias: elcodi.core.referral_program.factory.referral_line

    #
    # Factory for entity referral_hash
    #
    elcodi.core.referral_program.factory.referral_hash:
        class: %elcodi.core.referral_program.factory.referral_hash.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_hash.class%"]]

    elcodi.factory.referral_hash:
        alias: elcodi.core.referral_program.factory.referral_hash

    #
    # Factory for entity invitation
    #
    elcodi.core.referral_program.factory.invitation:
        class: %elcodi.core.referral_program.factory.invitation.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.invitation.class%"]]

    elcodi.factory.invitation:
        alias: elcodi.core.referral_program.factory.invitation

    #
    # Factory for entity invitation_bag
    #
    elcodi.core.referral_program.factory.invitation_bag:
        class: %elcodi.core.referral_program.factory.invitation_bag.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.invitation_bag.class%"]]

    elcodi.factory.invitation_bag:
        alias: elcodi.core.referral_program.factory.invitation_bag
