services:

    #
    # Repositories
    #

    #
    # Repository for entity referral_hash
    #
    elcodi.repository.referral_hash:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.referral_program.entity.referral_hash.class%

    #
    # Repository for entity referral_line
    #
    elcodi.repository.referral_line:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.referral_program.entity.referral_line.class%

    #
    # Repository for entity referral_rule
    #
    elcodi.repository.referral_rule:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.referral_program.entity.referral_rule.class%
